// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_YOGI_SIR_H_
#define FLATBUFFERS_GENERATED_COMMON_YOGI_SIR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Yogi {
namespace Sir {

struct SourcePosition;
struct SourcePositionBuilder;

struct TypeRef;
struct TypeRefBuilder;

enum TypeKind : int8_t {
  TypeKind_unknown = 0,
  TypeKind_number_type = 1,
  TypeKind_string_type = 2,
  TypeKind_boolean_type = 3,
  TypeKind_null_type = 4,
  TypeKind_undefined_type = 5,
  TypeKind_void_type = 6,
  TypeKind_any_type = 7,
  TypeKind_unknown_type = 8,
  TypeKind_never_type = 9,
  TypeKind_union_type = 10,
  TypeKind_intersection_type = 11,
  TypeKind_type_reference = 12,
  TypeKind_array_type = 13,
  TypeKind_tuple_type = 14,
  TypeKind_function_type = 15,
  TypeKind_type_literal = 16,
  TypeKind_MIN = TypeKind_unknown,
  TypeKind_MAX = TypeKind_type_literal
};

inline const TypeKind (&EnumValuesTypeKind())[17] {
  static const TypeKind values[] = {
    TypeKind_unknown,
    TypeKind_number_type,
    TypeKind_string_type,
    TypeKind_boolean_type,
    TypeKind_null_type,
    TypeKind_undefined_type,
    TypeKind_void_type,
    TypeKind_any_type,
    TypeKind_unknown_type,
    TypeKind_never_type,
    TypeKind_union_type,
    TypeKind_intersection_type,
    TypeKind_type_reference,
    TypeKind_array_type,
    TypeKind_tuple_type,
    TypeKind_function_type,
    TypeKind_type_literal
  };
  return values;
}

inline const char * const *EnumNamesTypeKind() {
  static const char * const names[18] = {
    "unknown",
    "number_type",
    "string_type",
    "boolean_type",
    "null_type",
    "undefined_type",
    "void_type",
    "any_type",
    "unknown_type",
    "never_type",
    "union_type",
    "intersection_type",
    "type_reference",
    "array_type",
    "tuple_type",
    "function_type",
    "type_literal",
    nullptr
  };
  return names;
}

inline const char *EnumNameTypeKind(TypeKind e) {
  if (::flatbuffers::IsOutRange(e, TypeKind_unknown, TypeKind_type_literal)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTypeKind()[index];
}

struct SourcePosition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SourcePositionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LINE = 4,
    VT_CHARACTER = 6
  };
  int32_t line() const {
    return GetField<int32_t>(VT_LINE, 0);
  }
  int32_t character() const {
    return GetField<int32_t>(VT_CHARACTER, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_LINE, 4) &&
           VerifyField<int32_t>(verifier, VT_CHARACTER, 4) &&
           verifier.EndTable();
  }
};

struct SourcePositionBuilder {
  typedef SourcePosition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_line(int32_t line) {
    fbb_.AddElement<int32_t>(SourcePosition::VT_LINE, line, 0);
  }
  void add_character(int32_t character) {
    fbb_.AddElement<int32_t>(SourcePosition::VT_CHARACTER, character, 0);
  }
  explicit SourcePositionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SourcePosition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SourcePosition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SourcePosition> CreateSourcePosition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t line = 0,
    int32_t character = 0) {
  SourcePositionBuilder builder_(_fbb);
  builder_.add_character(character);
  builder_.add_line(line);
  return builder_.Finish();
}

struct TypeRef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TypeRefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_RAW = 6,
    VT_NAME = 8,
    VT_TYPES = 10,
    VT_ELEMENT_TYPE = 12,
    VT_RESOLVED = 14,
    VT_FIXED = 16,
    VT_SHAPE = 18
  };
  Yogi::Sir::TypeKind kind() const {
    return static_cast<Yogi::Sir::TypeKind>(GetField<int8_t>(VT_KIND, 0));
  }
  const ::flatbuffers::String *raw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RAW);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Sir::TypeRef>> *types() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Sir::TypeRef>> *>(VT_TYPES);
  }
  const Yogi::Sir::TypeRef *element_type() const {
    return GetPointer<const Yogi::Sir::TypeRef *>(VT_ELEMENT_TYPE);
  }
  const Yogi::Sir::TypeRef *resolved() const {
    return GetPointer<const Yogi::Sir::TypeRef *>(VT_RESOLVED);
  }
  bool fixed() const {
    return GetField<uint8_t>(VT_FIXED, 0) != 0;
  }
  const ::flatbuffers::Vector<int32_t> *shape() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_SHAPE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           VerifyOffset(verifier, VT_RAW) &&
           verifier.VerifyString(raw()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TYPES) &&
           verifier.VerifyVector(types()) &&
           verifier.VerifyVectorOfTables(types()) &&
           VerifyOffset(verifier, VT_ELEMENT_TYPE) &&
           verifier.VerifyTable(element_type()) &&
           VerifyOffset(verifier, VT_RESOLVED) &&
           verifier.VerifyTable(resolved()) &&
           VerifyField<uint8_t>(verifier, VT_FIXED, 1) &&
           VerifyOffset(verifier, VT_SHAPE) &&
           verifier.VerifyVector(shape()) &&
           verifier.EndTable();
  }
};

struct TypeRefBuilder {
  typedef TypeRef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(Yogi::Sir::TypeKind kind) {
    fbb_.AddElement<int8_t>(TypeRef::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  void add_raw(::flatbuffers::Offset<::flatbuffers::String> raw) {
    fbb_.AddOffset(TypeRef::VT_RAW, raw);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(TypeRef::VT_NAME, name);
  }
  void add_types(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Sir::TypeRef>>> types) {
    fbb_.AddOffset(TypeRef::VT_TYPES, types);
  }
  void add_element_type(::flatbuffers::Offset<Yogi::Sir::TypeRef> element_type) {
    fbb_.AddOffset(TypeRef::VT_ELEMENT_TYPE, element_type);
  }
  void add_resolved(::flatbuffers::Offset<Yogi::Sir::TypeRef> resolved) {
    fbb_.AddOffset(TypeRef::VT_RESOLVED, resolved);
  }
  void add_fixed(bool fixed) {
    fbb_.AddElement<uint8_t>(TypeRef::VT_FIXED, static_cast<uint8_t>(fixed), 0);
  }
  void add_shape(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> shape) {
    fbb_.AddOffset(TypeRef::VT_SHAPE, shape);
  }
  explicit TypeRefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TypeRef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TypeRef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TypeRef> CreateTypeRef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Sir::TypeKind kind = Yogi::Sir::TypeKind_unknown,
    ::flatbuffers::Offset<::flatbuffers::String> raw = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Sir::TypeRef>>> types = 0,
    ::flatbuffers::Offset<Yogi::Sir::TypeRef> element_type = 0,
    ::flatbuffers::Offset<Yogi::Sir::TypeRef> resolved = 0,
    bool fixed = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> shape = 0) {
  TypeRefBuilder builder_(_fbb);
  builder_.add_shape(shape);
  builder_.add_resolved(resolved);
  builder_.add_element_type(element_type);
  builder_.add_types(types);
  builder_.add_name(name);
  builder_.add_raw(raw);
  builder_.add_fixed(fixed);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TypeRef> CreateTypeRefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Sir::TypeKind kind = Yogi::Sir::TypeKind_unknown,
    const char *raw = nullptr,
    const char *name = nullptr,
    const std::vector<::flatbuffers::Offset<Yogi::Sir::TypeRef>> *types = nullptr,
    ::flatbuffers::Offset<Yogi::Sir::TypeRef> element_type = 0,
    ::flatbuffers::Offset<Yogi::Sir::TypeRef> resolved = 0,
    bool fixed = false,
    const std::vector<int32_t> *shape = nullptr) {
  auto raw__ = raw ? _fbb.CreateString(raw) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto types__ = types ? _fbb.CreateVector<::flatbuffers::Offset<Yogi::Sir::TypeRef>>(*types) : 0;
  auto shape__ = shape ? _fbb.CreateVector<int32_t>(*shape) : 0;
  return Yogi::Sir::CreateTypeRef(
      _fbb,
      kind,
      raw__,
      name__,
      types__,
      element_type,
      resolved,
      fixed,
      shape__);
}

}  // namespace Sir
}  // namespace Yogi

#endif  // FLATBUFFERS_GENERATED_COMMON_YOGI_SIR_H_
