// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONSTANTS_YOGI_SIR_H_
#define FLATBUFFERS_GENERATED_CONSTANTS_YOGI_SIR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"

namespace Yogi {
namespace Sir {

struct NumberConstant;
struct NumberConstantBuilder;

struct StringConstant;
struct StringConstantBuilder;

struct BooleanConstant;
struct BooleanConstantBuilder;

struct NullConstant;
struct NullConstantBuilder;

struct UndefinedConstant;
struct UndefinedConstantBuilder;

struct Constant;
struct ConstantBuilder;

enum ConstantValue : uint8_t {
  ConstantValue_NONE = 0,
  ConstantValue_NumberConstant = 1,
  ConstantValue_StringConstant = 2,
  ConstantValue_BooleanConstant = 3,
  ConstantValue_NullConstant = 4,
  ConstantValue_UndefinedConstant = 5,
  ConstantValue_MIN = ConstantValue_NONE,
  ConstantValue_MAX = ConstantValue_UndefinedConstant
};

inline const ConstantValue (&EnumValuesConstantValue())[6] {
  static const ConstantValue values[] = {
    ConstantValue_NONE,
    ConstantValue_NumberConstant,
    ConstantValue_StringConstant,
    ConstantValue_BooleanConstant,
    ConstantValue_NullConstant,
    ConstantValue_UndefinedConstant
  };
  return values;
}

inline const char * const *EnumNamesConstantValue() {
  static const char * const names[7] = {
    "NONE",
    "NumberConstant",
    "StringConstant",
    "BooleanConstant",
    "NullConstant",
    "UndefinedConstant",
    nullptr
  };
  return names;
}

inline const char *EnumNameConstantValue(ConstantValue e) {
  if (::flatbuffers::IsOutRange(e, ConstantValue_NONE, ConstantValue_UndefinedConstant)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesConstantValue()[index];
}

template<typename T> struct ConstantValueTraits {
  static const ConstantValue enum_value = ConstantValue_NONE;
};

template<> struct ConstantValueTraits<Yogi::Sir::NumberConstant> {
  static const ConstantValue enum_value = ConstantValue_NumberConstant;
};

template<> struct ConstantValueTraits<Yogi::Sir::StringConstant> {
  static const ConstantValue enum_value = ConstantValue_StringConstant;
};

template<> struct ConstantValueTraits<Yogi::Sir::BooleanConstant> {
  static const ConstantValue enum_value = ConstantValue_BooleanConstant;
};

template<> struct ConstantValueTraits<Yogi::Sir::NullConstant> {
  static const ConstantValue enum_value = ConstantValue_NullConstant;
};

template<> struct ConstantValueTraits<Yogi::Sir::UndefinedConstant> {
  static const ConstantValue enum_value = ConstantValue_UndefinedConstant;
};

template <bool B = false>
bool VerifyConstantValue(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ConstantValue type);
template <bool B = false>
bool VerifyConstantValueVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct NumberConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NumberConstantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct NumberConstantBuilder {
  typedef NumberConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(double value) {
    fbb_.AddElement<double>(NumberConstant::VT_VALUE, value, 0.0);
  }
  explicit NumberConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NumberConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NumberConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NumberConstant> CreateNumberConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double value = 0.0) {
  NumberConstantBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct StringConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringConstantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct StringConstantBuilder {
  typedef StringConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(StringConstant::VT_VALUE, value);
  }
  explicit StringConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StringConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StringConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StringConstant> CreateStringConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  StringConstantBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StringConstant> CreateStringConstantDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return Yogi::Sir::CreateStringConstant(
      _fbb,
      value__);
}

struct BooleanConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BooleanConstantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  bool value() const {
    return GetField<uint8_t>(VT_VALUE, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE, 1) &&
           verifier.EndTable();
  }
};

struct BooleanConstantBuilder {
  typedef BooleanConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(bool value) {
    fbb_.AddElement<uint8_t>(BooleanConstant::VT_VALUE, static_cast<uint8_t>(value), 0);
  }
  explicit BooleanConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BooleanConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BooleanConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BooleanConstant> CreateBooleanConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool value = false) {
  BooleanConstantBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NullConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NullConstantBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct NullConstantBuilder {
  typedef NullConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit NullConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NullConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NullConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NullConstant> CreateNullConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  NullConstantBuilder builder_(_fbb);
  return builder_.Finish();
}

struct UndefinedConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UndefinedConstantBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UndefinedConstantBuilder {
  typedef UndefinedConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UndefinedConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UndefinedConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UndefinedConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UndefinedConstant> CreateUndefinedConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UndefinedConstantBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Constant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConstantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_RAW = 6,
    VT_SOURCE = 8,
    VT_POSITION = 10,
    VT_VALUE_TYPE = 12,
    VT_VALUE = 14
  };
  const Yogi::Sir::TypeRef *type() const {
    return GetPointer<const Yogi::Sir::TypeRef *>(VT_TYPE);
  }
  const ::flatbuffers::String *raw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RAW);
  }
  const ::flatbuffers::String *source() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE);
  }
  const Yogi::Sir::SourcePosition *position() const {
    return GetPointer<const Yogi::Sir::SourcePosition *>(VT_POSITION);
  }
  Yogi::Sir::ConstantValue value_type() const {
    return static_cast<Yogi::Sir::ConstantValue>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const Yogi::Sir::NumberConstant *value_as_NumberConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_NumberConstant ? static_cast<const Yogi::Sir::NumberConstant *>(value()) : nullptr;
  }
  const Yogi::Sir::StringConstant *value_as_StringConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_StringConstant ? static_cast<const Yogi::Sir::StringConstant *>(value()) : nullptr;
  }
  const Yogi::Sir::BooleanConstant *value_as_BooleanConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_BooleanConstant ? static_cast<const Yogi::Sir::BooleanConstant *>(value()) : nullptr;
  }
  const Yogi::Sir::NullConstant *value_as_NullConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_NullConstant ? static_cast<const Yogi::Sir::NullConstant *>(value()) : nullptr;
  }
  const Yogi::Sir::UndefinedConstant *value_as_UndefinedConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_UndefinedConstant ? static_cast<const Yogi::Sir::UndefinedConstant *>(value()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           VerifyOffset(verifier, VT_RAW) &&
           verifier.VerifyString(raw()) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyString(source()) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifyConstantValue(verifier, value(), value_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Yogi::Sir::NumberConstant *Constant::value_as<Yogi::Sir::NumberConstant>() const {
  return value_as_NumberConstant();
}

template<> inline const Yogi::Sir::StringConstant *Constant::value_as<Yogi::Sir::StringConstant>() const {
  return value_as_StringConstant();
}

template<> inline const Yogi::Sir::BooleanConstant *Constant::value_as<Yogi::Sir::BooleanConstant>() const {
  return value_as_BooleanConstant();
}

template<> inline const Yogi::Sir::NullConstant *Constant::value_as<Yogi::Sir::NullConstant>() const {
  return value_as_NullConstant();
}

template<> inline const Yogi::Sir::UndefinedConstant *Constant::value_as<Yogi::Sir::UndefinedConstant>() const {
  return value_as_UndefinedConstant();
}

struct ConstantBuilder {
  typedef Constant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(::flatbuffers::Offset<Yogi::Sir::TypeRef> type) {
    fbb_.AddOffset(Constant::VT_TYPE, type);
  }
  void add_raw(::flatbuffers::Offset<::flatbuffers::String> raw) {
    fbb_.AddOffset(Constant::VT_RAW, raw);
  }
  void add_source(::flatbuffers::Offset<::flatbuffers::String> source) {
    fbb_.AddOffset(Constant::VT_SOURCE, source);
  }
  void add_position(::flatbuffers::Offset<Yogi::Sir::SourcePosition> position) {
    fbb_.AddOffset(Constant::VT_POSITION, position);
  }
  void add_value_type(Yogi::Sir::ConstantValue value_type) {
    fbb_.AddElement<uint8_t>(Constant::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(Constant::VT_VALUE, value);
  }
  explicit ConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Constant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Constant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Constant> CreateConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Yogi::Sir::TypeRef> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> raw = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source = 0,
    ::flatbuffers::Offset<Yogi::Sir::SourcePosition> position = 0,
    Yogi::Sir::ConstantValue value_type = Yogi::Sir::ConstantValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  ConstantBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_position(position);
  builder_.add_source(source);
  builder_.add_raw(raw);
  builder_.add_type(type);
  builder_.add_value_type(value_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Constant> CreateConstantDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Yogi::Sir::TypeRef> type = 0,
    const char *raw = nullptr,
    const char *source = nullptr,
    ::flatbuffers::Offset<Yogi::Sir::SourcePosition> position = 0,
    Yogi::Sir::ConstantValue value_type = Yogi::Sir::ConstantValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  auto raw__ = raw ? _fbb.CreateString(raw) : 0;
  auto source__ = source ? _fbb.CreateString(source) : 0;
  return Yogi::Sir::CreateConstant(
      _fbb,
      type,
      raw__,
      source__,
      position,
      value_type,
      value);
}

template <bool B>
inline bool VerifyConstantValue(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ConstantValue type) {
  switch (type) {
    case ConstantValue_NONE: {
      return true;
    }
    case ConstantValue_NumberConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::NumberConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConstantValue_StringConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::StringConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConstantValue_BooleanConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::BooleanConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConstantValue_NullConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::NullConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConstantValue_UndefinedConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::UndefinedConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyConstantValueVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyConstantValue(
        verifier,  values->Get(i), types->GetEnum<ConstantValue>(i))) {
      return false;
    }
  }
  return true;
}

}  // namespace Sir
}  // namespace Yogi

#endif  // FLATBUFFERS_GENERATED_CONSTANTS_YOGI_SIR_H_
