// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAIN_YOGI_MAIN_H_
#define FLATBUFFERS_GENERATED_MAIN_YOGI_MAIN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Yogi {
namespace Build {

struct ModuleMeta;
struct ModuleMetaBuilder;

struct LinkEntry;
struct LinkEntryBuilder;

struct Meta;
struct MetaBuilder;

}  // namespace Build

namespace Sir {

struct SourcePosition;
struct SourcePositionBuilder;

struct TypeRef;
struct TypeRefBuilder;

struct NumberConstant;
struct NumberConstantBuilder;

struct StringConstant;
struct StringConstantBuilder;

struct BooleanConstant;
struct BooleanConstantBuilder;

struct NullConstant;
struct NullConstantBuilder;

struct UndefinedConstant;
struct UndefinedConstantBuilder;

struct Constant;
struct ConstantBuilder;

struct SirNode;
struct SirNodeBuilder;

struct Module;
struct ModuleBuilder;

}  // namespace Sir

namespace Main {

struct Root;
struct RootBuilder;

}  // namespace Main

namespace Build {

enum LinkKind : int8_t {
  LinkKind_object = 0,
  LinkKind_static_library = 1,
  LinkKind_dynamic_library = 2,
  LinkKind_system_library = 3,
  LinkKind_MIN = LinkKind_object,
  LinkKind_MAX = LinkKind_system_library
};

inline const LinkKind (&EnumValuesLinkKind())[4] {
  static const LinkKind values[] = {
    LinkKind_object,
    LinkKind_static_library,
    LinkKind_dynamic_library,
    LinkKind_system_library
  };
  return values;
}

inline const char * const *EnumNamesLinkKind() {
  static const char * const names[5] = {
    "object",
    "static_library",
    "dynamic_library",
    "system_library",
    nullptr
  };
  return names;
}

inline const char *EnumNameLinkKind(LinkKind e) {
  if (::flatbuffers::IsOutRange(e, LinkKind_object, LinkKind_system_library)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLinkKind()[index];
}

}  // namespace Build

namespace Sir {

enum TypeKind : int8_t {
  TypeKind_unknown = 0,
  TypeKind_number_type = 1,
  TypeKind_string_type = 2,
  TypeKind_boolean_type = 3,
  TypeKind_null_type = 4,
  TypeKind_undefined_type = 5,
  TypeKind_MIN = TypeKind_unknown,
  TypeKind_MAX = TypeKind_undefined_type
};

inline const TypeKind (&EnumValuesTypeKind())[6] {
  static const TypeKind values[] = {
    TypeKind_unknown,
    TypeKind_number_type,
    TypeKind_string_type,
    TypeKind_boolean_type,
    TypeKind_null_type,
    TypeKind_undefined_type
  };
  return values;
}

inline const char * const *EnumNamesTypeKind() {
  static const char * const names[7] = {
    "unknown",
    "number_type",
    "string_type",
    "boolean_type",
    "null_type",
    "undefined_type",
    nullptr
  };
  return names;
}

inline const char *EnumNameTypeKind(TypeKind e) {
  if (::flatbuffers::IsOutRange(e, TypeKind_unknown, TypeKind_undefined_type)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTypeKind()[index];
}

enum ConstantValue : uint8_t {
  ConstantValue_NONE = 0,
  ConstantValue_NumberConstant = 1,
  ConstantValue_StringConstant = 2,
  ConstantValue_BooleanConstant = 3,
  ConstantValue_NullConstant = 4,
  ConstantValue_UndefinedConstant = 5,
  ConstantValue_MIN = ConstantValue_NONE,
  ConstantValue_MAX = ConstantValue_UndefinedConstant
};

inline const ConstantValue (&EnumValuesConstantValue())[6] {
  static const ConstantValue values[] = {
    ConstantValue_NONE,
    ConstantValue_NumberConstant,
    ConstantValue_StringConstant,
    ConstantValue_BooleanConstant,
    ConstantValue_NullConstant,
    ConstantValue_UndefinedConstant
  };
  return values;
}

inline const char * const *EnumNamesConstantValue() {
  static const char * const names[7] = {
    "NONE",
    "NumberConstant",
    "StringConstant",
    "BooleanConstant",
    "NullConstant",
    "UndefinedConstant",
    nullptr
  };
  return names;
}

inline const char *EnumNameConstantValue(ConstantValue e) {
  if (::flatbuffers::IsOutRange(e, ConstantValue_NONE, ConstantValue_UndefinedConstant)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesConstantValue()[index];
}

template<typename T> struct ConstantValueTraits {
  static const ConstantValue enum_value = ConstantValue_NONE;
};

template<> struct ConstantValueTraits<Yogi::Sir::NumberConstant> {
  static const ConstantValue enum_value = ConstantValue_NumberConstant;
};

template<> struct ConstantValueTraits<Yogi::Sir::StringConstant> {
  static const ConstantValue enum_value = ConstantValue_StringConstant;
};

template<> struct ConstantValueTraits<Yogi::Sir::BooleanConstant> {
  static const ConstantValue enum_value = ConstantValue_BooleanConstant;
};

template<> struct ConstantValueTraits<Yogi::Sir::NullConstant> {
  static const ConstantValue enum_value = ConstantValue_NullConstant;
};

template<> struct ConstantValueTraits<Yogi::Sir::UndefinedConstant> {
  static const ConstantValue enum_value = ConstantValue_UndefinedConstant;
};

template <bool B = false>
bool VerifyConstantValue(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ConstantValue type);
template <bool B = false>
bool VerifyConstantValueVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum SirNodeValue : uint8_t {
  SirNodeValue_NONE = 0,
  SirNodeValue_Constant = 1,
  SirNodeValue_MIN = SirNodeValue_NONE,
  SirNodeValue_MAX = SirNodeValue_Constant
};

inline const SirNodeValue (&EnumValuesSirNodeValue())[2] {
  static const SirNodeValue values[] = {
    SirNodeValue_NONE,
    SirNodeValue_Constant
  };
  return values;
}

inline const char * const *EnumNamesSirNodeValue() {
  static const char * const names[3] = {
    "NONE",
    "Constant",
    nullptr
  };
  return names;
}

inline const char *EnumNameSirNodeValue(SirNodeValue e) {
  if (::flatbuffers::IsOutRange(e, SirNodeValue_NONE, SirNodeValue_Constant)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSirNodeValue()[index];
}

template<typename T> struct SirNodeValueTraits {
  static const SirNodeValue enum_value = SirNodeValue_NONE;
};

template<> struct SirNodeValueTraits<Yogi::Sir::Constant> {
  static const SirNodeValue enum_value = SirNodeValue_Constant;
};

template <bool B = false>
bool VerifySirNodeValue(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SirNodeValue type);
template <bool B = false>
bool VerifySirNodeValueVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

}  // namespace Sir

namespace Build {

struct ModuleMeta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModuleMetaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SOURCE_PATH = 6,
    VT_SOURCE_HASH = 8,
    VT_AST_HASH = 10,
    VT_SIR_HASH = 12,
    VT_SHOULD_LOWER = 14,
    VT_IS_ENTRY = 16
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *source_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_PATH);
  }
  const ::flatbuffers::String *source_hash() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_HASH);
  }
  const ::flatbuffers::String *ast_hash() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AST_HASH);
  }
  const ::flatbuffers::String *sir_hash() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SIR_HASH);
  }
  bool should_lower() const {
    return GetField<uint8_t>(VT_SHOULD_LOWER, 0) != 0;
  }
  bool is_entry() const {
    return GetField<uint8_t>(VT_IS_ENTRY, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_SOURCE_PATH) &&
           verifier.VerifyString(source_path()) &&
           VerifyOffset(verifier, VT_SOURCE_HASH) &&
           verifier.VerifyString(source_hash()) &&
           VerifyOffset(verifier, VT_AST_HASH) &&
           verifier.VerifyString(ast_hash()) &&
           VerifyOffset(verifier, VT_SIR_HASH) &&
           verifier.VerifyString(sir_hash()) &&
           VerifyField<uint8_t>(verifier, VT_SHOULD_LOWER, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_ENTRY, 1) &&
           verifier.EndTable();
  }
};

struct ModuleMetaBuilder {
  typedef ModuleMeta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(ModuleMeta::VT_NAME, name);
  }
  void add_source_path(::flatbuffers::Offset<::flatbuffers::String> source_path) {
    fbb_.AddOffset(ModuleMeta::VT_SOURCE_PATH, source_path);
  }
  void add_source_hash(::flatbuffers::Offset<::flatbuffers::String> source_hash) {
    fbb_.AddOffset(ModuleMeta::VT_SOURCE_HASH, source_hash);
  }
  void add_ast_hash(::flatbuffers::Offset<::flatbuffers::String> ast_hash) {
    fbb_.AddOffset(ModuleMeta::VT_AST_HASH, ast_hash);
  }
  void add_sir_hash(::flatbuffers::Offset<::flatbuffers::String> sir_hash) {
    fbb_.AddOffset(ModuleMeta::VT_SIR_HASH, sir_hash);
  }
  void add_should_lower(bool should_lower) {
    fbb_.AddElement<uint8_t>(ModuleMeta::VT_SHOULD_LOWER, static_cast<uint8_t>(should_lower), 0);
  }
  void add_is_entry(bool is_entry) {
    fbb_.AddElement<uint8_t>(ModuleMeta::VT_IS_ENTRY, static_cast<uint8_t>(is_entry), 0);
  }
  explicit ModuleMetaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModuleMeta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModuleMeta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModuleMeta> CreateModuleMeta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ast_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sir_hash = 0,
    bool should_lower = false,
    bool is_entry = false) {
  ModuleMetaBuilder builder_(_fbb);
  builder_.add_sir_hash(sir_hash);
  builder_.add_ast_hash(ast_hash);
  builder_.add_source_hash(source_hash);
  builder_.add_source_path(source_path);
  builder_.add_name(name);
  builder_.add_is_entry(is_entry);
  builder_.add_should_lower(should_lower);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModuleMeta> CreateModuleMetaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *source_path = nullptr,
    const char *source_hash = nullptr,
    const char *ast_hash = nullptr,
    const char *sir_hash = nullptr,
    bool should_lower = false,
    bool is_entry = false) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto source_path__ = source_path ? _fbb.CreateString(source_path) : 0;
  auto source_hash__ = source_hash ? _fbb.CreateString(source_hash) : 0;
  auto ast_hash__ = ast_hash ? _fbb.CreateString(ast_hash) : 0;
  auto sir_hash__ = sir_hash ? _fbb.CreateString(sir_hash) : 0;
  return Yogi::Build::CreateModuleMeta(
      _fbb,
      name__,
      source_path__,
      source_hash__,
      ast_hash__,
      sir_hash__,
      should_lower,
      is_entry);
}

struct LinkEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LinkEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_PATH = 6
  };
  Yogi::Build::LinkKind kind() const {
    return static_cast<Yogi::Build::LinkKind>(GetField<int8_t>(VT_KIND, 0));
  }
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           verifier.EndTable();
  }
};

struct LinkEntryBuilder {
  typedef LinkEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(Yogi::Build::LinkKind kind) {
    fbb_.AddElement<int8_t>(LinkEntry::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(LinkEntry::VT_PATH, path);
  }
  explicit LinkEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LinkEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LinkEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LinkEntry> CreateLinkEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Build::LinkKind kind = Yogi::Build::LinkKind_object,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0) {
  LinkEntryBuilder builder_(_fbb);
  builder_.add_path(path);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LinkEntry> CreateLinkEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Build::LinkKind kind = Yogi::Build::LinkKind_object,
    const char *path = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return Yogi::Build::CreateLinkEntry(
      _fbb,
      kind,
      path__);
}

struct Meta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MetaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOT_PATH = 4,
    VT_CACHE_PATH = 6,
    VT_OUTPUT_PATH = 8,
    VT_MODULES = 10,
    VT_LINKS = 12
  };
  const ::flatbuffers::String *root_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROOT_PATH);
  }
  const ::flatbuffers::String *cache_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CACHE_PATH);
  }
  const ::flatbuffers::String *output_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OUTPUT_PATH);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>> *modules() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>> *>(VT_MODULES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>> *links() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>> *>(VT_LINKS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ROOT_PATH) &&
           verifier.VerifyString(root_path()) &&
           VerifyOffset(verifier, VT_CACHE_PATH) &&
           verifier.VerifyString(cache_path()) &&
           VerifyOffset(verifier, VT_OUTPUT_PATH) &&
           verifier.VerifyString(output_path()) &&
           VerifyOffset(verifier, VT_MODULES) &&
           verifier.VerifyVector(modules()) &&
           verifier.VerifyVectorOfTables(modules()) &&
           VerifyOffset(verifier, VT_LINKS) &&
           verifier.VerifyVector(links()) &&
           verifier.VerifyVectorOfTables(links()) &&
           verifier.EndTable();
  }
};

struct MetaBuilder {
  typedef Meta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_root_path(::flatbuffers::Offset<::flatbuffers::String> root_path) {
    fbb_.AddOffset(Meta::VT_ROOT_PATH, root_path);
  }
  void add_cache_path(::flatbuffers::Offset<::flatbuffers::String> cache_path) {
    fbb_.AddOffset(Meta::VT_CACHE_PATH, cache_path);
  }
  void add_output_path(::flatbuffers::Offset<::flatbuffers::String> output_path) {
    fbb_.AddOffset(Meta::VT_OUTPUT_PATH, output_path);
  }
  void add_modules(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>>> modules) {
    fbb_.AddOffset(Meta::VT_MODULES, modules);
  }
  void add_links(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>>> links) {
    fbb_.AddOffset(Meta::VT_LINKS, links);
  }
  explicit MetaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Meta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Meta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Meta> CreateMeta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> root_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cache_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> output_path = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>>> modules = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>>> links = 0) {
  MetaBuilder builder_(_fbb);
  builder_.add_links(links);
  builder_.add_modules(modules);
  builder_.add_output_path(output_path);
  builder_.add_cache_path(cache_path);
  builder_.add_root_path(root_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Meta> CreateMetaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *root_path = nullptr,
    const char *cache_path = nullptr,
    const char *output_path = nullptr,
    const std::vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>> *modules = nullptr,
    const std::vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>> *links = nullptr) {
  auto root_path__ = root_path ? _fbb.CreateString(root_path) : 0;
  auto cache_path__ = cache_path ? _fbb.CreateString(cache_path) : 0;
  auto output_path__ = output_path ? _fbb.CreateString(output_path) : 0;
  auto modules__ = modules ? _fbb.CreateVector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>>(*modules) : 0;
  auto links__ = links ? _fbb.CreateVector<::flatbuffers::Offset<Yogi::Build::LinkEntry>>(*links) : 0;
  return Yogi::Build::CreateMeta(
      _fbb,
      root_path__,
      cache_path__,
      output_path__,
      modules__,
      links__);
}

}  // namespace Build

namespace Sir {

struct SourcePosition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SourcePositionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LINE = 4,
    VT_CHARACTER = 6
  };
  int32_t line() const {
    return GetField<int32_t>(VT_LINE, 0);
  }
  int32_t character() const {
    return GetField<int32_t>(VT_CHARACTER, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_LINE, 4) &&
           VerifyField<int32_t>(verifier, VT_CHARACTER, 4) &&
           verifier.EndTable();
  }
};

struct SourcePositionBuilder {
  typedef SourcePosition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_line(int32_t line) {
    fbb_.AddElement<int32_t>(SourcePosition::VT_LINE, line, 0);
  }
  void add_character(int32_t character) {
    fbb_.AddElement<int32_t>(SourcePosition::VT_CHARACTER, character, 0);
  }
  explicit SourcePositionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SourcePosition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SourcePosition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SourcePosition> CreateSourcePosition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t line = 0,
    int32_t character = 0) {
  SourcePositionBuilder builder_(_fbb);
  builder_.add_character(character);
  builder_.add_line(line);
  return builder_.Finish();
}

struct TypeRef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TypeRefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_RAW = 6
  };
  Yogi::Sir::TypeKind kind() const {
    return static_cast<Yogi::Sir::TypeKind>(GetField<int8_t>(VT_KIND, 0));
  }
  const ::flatbuffers::String *raw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RAW);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           VerifyOffset(verifier, VT_RAW) &&
           verifier.VerifyString(raw()) &&
           verifier.EndTable();
  }
};

struct TypeRefBuilder {
  typedef TypeRef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(Yogi::Sir::TypeKind kind) {
    fbb_.AddElement<int8_t>(TypeRef::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  void add_raw(::flatbuffers::Offset<::flatbuffers::String> raw) {
    fbb_.AddOffset(TypeRef::VT_RAW, raw);
  }
  explicit TypeRefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TypeRef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TypeRef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TypeRef> CreateTypeRef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Sir::TypeKind kind = Yogi::Sir::TypeKind_unknown,
    ::flatbuffers::Offset<::flatbuffers::String> raw = 0) {
  TypeRefBuilder builder_(_fbb);
  builder_.add_raw(raw);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TypeRef> CreateTypeRefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Sir::TypeKind kind = Yogi::Sir::TypeKind_unknown,
    const char *raw = nullptr) {
  auto raw__ = raw ? _fbb.CreateString(raw) : 0;
  return Yogi::Sir::CreateTypeRef(
      _fbb,
      kind,
      raw__);
}

struct NumberConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NumberConstantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct NumberConstantBuilder {
  typedef NumberConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(double value) {
    fbb_.AddElement<double>(NumberConstant::VT_VALUE, value, 0.0);
  }
  explicit NumberConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NumberConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NumberConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NumberConstant> CreateNumberConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double value = 0.0) {
  NumberConstantBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct StringConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringConstantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct StringConstantBuilder {
  typedef StringConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(StringConstant::VT_VALUE, value);
  }
  explicit StringConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StringConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StringConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StringConstant> CreateStringConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  StringConstantBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StringConstant> CreateStringConstantDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return Yogi::Sir::CreateStringConstant(
      _fbb,
      value__);
}

struct BooleanConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BooleanConstantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  bool value() const {
    return GetField<uint8_t>(VT_VALUE, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE, 1) &&
           verifier.EndTable();
  }
};

struct BooleanConstantBuilder {
  typedef BooleanConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(bool value) {
    fbb_.AddElement<uint8_t>(BooleanConstant::VT_VALUE, static_cast<uint8_t>(value), 0);
  }
  explicit BooleanConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BooleanConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BooleanConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BooleanConstant> CreateBooleanConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool value = false) {
  BooleanConstantBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct NullConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NullConstantBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct NullConstantBuilder {
  typedef NullConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit NullConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NullConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NullConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NullConstant> CreateNullConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  NullConstantBuilder builder_(_fbb);
  return builder_.Finish();
}

struct UndefinedConstant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UndefinedConstantBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UndefinedConstantBuilder {
  typedef UndefinedConstant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UndefinedConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UndefinedConstant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UndefinedConstant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UndefinedConstant> CreateUndefinedConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UndefinedConstantBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Constant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConstantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_RAW = 6,
    VT_SOURCE = 8,
    VT_POSITION = 10,
    VT_VALUE_TYPE = 12,
    VT_VALUE = 14
  };
  const Yogi::Sir::TypeRef *type() const {
    return GetPointer<const Yogi::Sir::TypeRef *>(VT_TYPE);
  }
  const ::flatbuffers::String *raw() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RAW);
  }
  const ::flatbuffers::String *source() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE);
  }
  const Yogi::Sir::SourcePosition *position() const {
    return GetPointer<const Yogi::Sir::SourcePosition *>(VT_POSITION);
  }
  Yogi::Sir::ConstantValue value_type() const {
    return static_cast<Yogi::Sir::ConstantValue>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const Yogi::Sir::NumberConstant *value_as_NumberConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_NumberConstant ? static_cast<const Yogi::Sir::NumberConstant *>(value()) : nullptr;
  }
  const Yogi::Sir::StringConstant *value_as_StringConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_StringConstant ? static_cast<const Yogi::Sir::StringConstant *>(value()) : nullptr;
  }
  const Yogi::Sir::BooleanConstant *value_as_BooleanConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_BooleanConstant ? static_cast<const Yogi::Sir::BooleanConstant *>(value()) : nullptr;
  }
  const Yogi::Sir::NullConstant *value_as_NullConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_NullConstant ? static_cast<const Yogi::Sir::NullConstant *>(value()) : nullptr;
  }
  const Yogi::Sir::UndefinedConstant *value_as_UndefinedConstant() const {
    return value_type() == Yogi::Sir::ConstantValue_UndefinedConstant ? static_cast<const Yogi::Sir::UndefinedConstant *>(value()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           VerifyOffset(verifier, VT_RAW) &&
           verifier.VerifyString(raw()) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyString(source()) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifyConstantValue(verifier, value(), value_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Yogi::Sir::NumberConstant *Constant::value_as<Yogi::Sir::NumberConstant>() const {
  return value_as_NumberConstant();
}

template<> inline const Yogi::Sir::StringConstant *Constant::value_as<Yogi::Sir::StringConstant>() const {
  return value_as_StringConstant();
}

template<> inline const Yogi::Sir::BooleanConstant *Constant::value_as<Yogi::Sir::BooleanConstant>() const {
  return value_as_BooleanConstant();
}

template<> inline const Yogi::Sir::NullConstant *Constant::value_as<Yogi::Sir::NullConstant>() const {
  return value_as_NullConstant();
}

template<> inline const Yogi::Sir::UndefinedConstant *Constant::value_as<Yogi::Sir::UndefinedConstant>() const {
  return value_as_UndefinedConstant();
}

struct ConstantBuilder {
  typedef Constant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(::flatbuffers::Offset<Yogi::Sir::TypeRef> type) {
    fbb_.AddOffset(Constant::VT_TYPE, type);
  }
  void add_raw(::flatbuffers::Offset<::flatbuffers::String> raw) {
    fbb_.AddOffset(Constant::VT_RAW, raw);
  }
  void add_source(::flatbuffers::Offset<::flatbuffers::String> source) {
    fbb_.AddOffset(Constant::VT_SOURCE, source);
  }
  void add_position(::flatbuffers::Offset<Yogi::Sir::SourcePosition> position) {
    fbb_.AddOffset(Constant::VT_POSITION, position);
  }
  void add_value_type(Yogi::Sir::ConstantValue value_type) {
    fbb_.AddElement<uint8_t>(Constant::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(Constant::VT_VALUE, value);
  }
  explicit ConstantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Constant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Constant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Constant> CreateConstant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Yogi::Sir::TypeRef> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> raw = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source = 0,
    ::flatbuffers::Offset<Yogi::Sir::SourcePosition> position = 0,
    Yogi::Sir::ConstantValue value_type = Yogi::Sir::ConstantValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  ConstantBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_position(position);
  builder_.add_source(source);
  builder_.add_raw(raw);
  builder_.add_type(type);
  builder_.add_value_type(value_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Constant> CreateConstantDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Yogi::Sir::TypeRef> type = 0,
    const char *raw = nullptr,
    const char *source = nullptr,
    ::flatbuffers::Offset<Yogi::Sir::SourcePosition> position = 0,
    Yogi::Sir::ConstantValue value_type = Yogi::Sir::ConstantValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  auto raw__ = raw ? _fbb.CreateString(raw) : 0;
  auto source__ = source ? _fbb.CreateString(source) : 0;
  return Yogi::Sir::CreateConstant(
      _fbb,
      type,
      raw__,
      source__,
      position,
      value_type,
      value);
}

struct SirNode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SirNodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE_TYPE = 4,
    VT_VALUE = 6
  };
  Yogi::Sir::SirNodeValue value_type() const {
    return static_cast<Yogi::Sir::SirNodeValue>(GetField<uint8_t>(VT_VALUE_TYPE, 0));
  }
  const void *value() const {
    return GetPointer<const void *>(VT_VALUE);
  }
  template<typename T> const T *value_as() const;
  const Yogi::Sir::Constant *value_as_Constant() const {
    return value_type() == Yogi::Sir::SirNodeValue_Constant ? static_cast<const Yogi::Sir::Constant *>(value()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           VerifySirNodeValue(verifier, value(), value_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Yogi::Sir::Constant *SirNode::value_as<Yogi::Sir::Constant>() const {
  return value_as_Constant();
}

struct SirNodeBuilder {
  typedef SirNode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value_type(Yogi::Sir::SirNodeValue value_type) {
    fbb_.AddElement<uint8_t>(SirNode::VT_VALUE_TYPE, static_cast<uint8_t>(value_type), 0);
  }
  void add_value(::flatbuffers::Offset<void> value) {
    fbb_.AddOffset(SirNode::VT_VALUE, value);
  }
  explicit SirNodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SirNode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SirNode>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SirNode> CreateSirNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Sir::SirNodeValue value_type = Yogi::Sir::SirNodeValue_NONE,
    ::flatbuffers::Offset<void> value = 0) {
  SirNodeBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_value_type(value_type);
  return builder_.Finish();
}

struct Module FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModuleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE_PATH = 4,
    VT_NODES = 6
  };
  const ::flatbuffers::String *source_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_PATH);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Sir::SirNode>> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Sir::SirNode>> *>(VT_NODES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SOURCE_PATH) &&
           verifier.VerifyString(source_path()) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           verifier.EndTable();
  }
};

struct ModuleBuilder {
  typedef Module Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_source_path(::flatbuffers::Offset<::flatbuffers::String> source_path) {
    fbb_.AddOffset(Module::VT_SOURCE_PATH, source_path);
  }
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Sir::SirNode>>> nodes) {
    fbb_.AddOffset(Module::VT_NODES, nodes);
  }
  explicit ModuleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Module> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Module>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Module> CreateModule(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> source_path = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Sir::SirNode>>> nodes = 0) {
  ModuleBuilder builder_(_fbb);
  builder_.add_nodes(nodes);
  builder_.add_source_path(source_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Module> CreateModuleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *source_path = nullptr,
    const std::vector<::flatbuffers::Offset<Yogi::Sir::SirNode>> *nodes = nullptr) {
  auto source_path__ = source_path ? _fbb.CreateString(source_path) : 0;
  auto nodes__ = nodes ? _fbb.CreateVector<::flatbuffers::Offset<Yogi::Sir::SirNode>>(*nodes) : 0;
  return Yogi::Sir::CreateModule(
      _fbb,
      source_path__,
      nodes__);
}

}  // namespace Sir

namespace Main {

struct Root FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RootBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BUILD = 4,
    VT_SIR = 6
  };
  const Yogi::Build::Meta *build() const {
    return GetPointer<const Yogi::Build::Meta *>(VT_BUILD);
  }
  const Yogi::Sir::Module *sir() const {
    return GetPointer<const Yogi::Sir::Module *>(VT_SIR);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BUILD) &&
           verifier.VerifyTable(build()) &&
           VerifyOffset(verifier, VT_SIR) &&
           verifier.VerifyTable(sir()) &&
           verifier.EndTable();
  }
};

struct RootBuilder {
  typedef Root Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_build(::flatbuffers::Offset<Yogi::Build::Meta> build) {
    fbb_.AddOffset(Root::VT_BUILD, build);
  }
  void add_sir(::flatbuffers::Offset<Yogi::Sir::Module> sir) {
    fbb_.AddOffset(Root::VT_SIR, sir);
  }
  explicit RootBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Root> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Root>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Root> CreateRoot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Yogi::Build::Meta> build = 0,
    ::flatbuffers::Offset<Yogi::Sir::Module> sir = 0) {
  RootBuilder builder_(_fbb);
  builder_.add_sir(sir);
  builder_.add_build(build);
  return builder_.Finish();
}

}  // namespace Main

namespace Build {

}  // namespace Build

namespace Sir {

}  // namespace Sir

namespace Main {

}  // namespace Main

namespace Sir {

template <bool B>
inline bool VerifyConstantValue(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ConstantValue type) {
  switch (type) {
    case ConstantValue_NONE: {
      return true;
    }
    case ConstantValue_NumberConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::NumberConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConstantValue_StringConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::StringConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConstantValue_BooleanConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::BooleanConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConstantValue_NullConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::NullConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ConstantValue_UndefinedConstant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::UndefinedConstant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyConstantValueVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyConstantValue(
        verifier,  values->Get(i), types->GetEnum<ConstantValue>(i))) {
      return false;
    }
  }
  return true;
}

template <bool B>
inline bool VerifySirNodeValue(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SirNodeValue type) {
  switch (type) {
    case SirNodeValue_NONE: {
      return true;
    }
    case SirNodeValue_Constant: {
      auto ptr = reinterpret_cast<const Yogi::Sir::Constant *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifySirNodeValueVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySirNodeValue(
        verifier,  values->Get(i), types->GetEnum<SirNodeValue>(i))) {
      return false;
    }
  }
  return true;
}

}  // namespace Sir

namespace Main {

inline const Yogi::Main::Root *GetRoot(const void *buf) {
  return ::flatbuffers::GetRoot<Yogi::Main::Root>(buf);
}

inline const Yogi::Main::Root *GetSizePrefixedRoot(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Yogi::Main::Root>(buf);
}

template <bool B = false>
inline bool VerifyRootBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Yogi::Main::Root>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedRootBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Yogi::Main::Root>(nullptr);
}

inline void FinishRootBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Yogi::Main::Root> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRootBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Yogi::Main::Root> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Main
}  // namespace Yogi

#endif  // FLATBUFFERS_GENERATED_MAIN_YOGI_MAIN_H_
