// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_META_YOGI_BUILD_H_
#define FLATBUFFERS_GENERATED_META_YOGI_BUILD_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Yogi {
namespace Build {

struct ModuleMeta;
struct ModuleMetaBuilder;

struct LinkEntry;
struct LinkEntryBuilder;

struct Meta;
struct MetaBuilder;

enum LinkKind : int8_t {
  LinkKind_object = 0,
  LinkKind_static_library = 1,
  LinkKind_dynamic_library = 2,
  LinkKind_system_library = 3,
  LinkKind_MIN = LinkKind_object,
  LinkKind_MAX = LinkKind_system_library
};

inline const LinkKind (&EnumValuesLinkKind())[4] {
  static const LinkKind values[] = {
    LinkKind_object,
    LinkKind_static_library,
    LinkKind_dynamic_library,
    LinkKind_system_library
  };
  return values;
}

inline const char * const *EnumNamesLinkKind() {
  static const char * const names[5] = {
    "object",
    "static_library",
    "dynamic_library",
    "system_library",
    nullptr
  };
  return names;
}

inline const char *EnumNameLinkKind(LinkKind e) {
  if (::flatbuffers::IsOutRange(e, LinkKind_object, LinkKind_system_library)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLinkKind()[index];
}

struct ModuleMeta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModuleMetaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_ENTRY = 4,
    VT_ROOT_PATH = 6,
    VT_NAME = 8,
    VT_SHOULD_LOWER = 10,
    VT_SOURCE_PATH = 12,
    VT_AST_PATH = 14,
    VT_OBJECT_PATH = 16,
    VT_SIR_PATH = 18,
    VT_SOURCE_HASH = 20,
    VT_AST_HASH = 22,
    VT_SIR_HASH = 24
  };
  bool is_entry() const {
    return GetField<uint8_t>(VT_IS_ENTRY, 0) != 0;
  }
  const ::flatbuffers::String *root_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROOT_PATH);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool should_lower() const {
    return GetField<uint8_t>(VT_SHOULD_LOWER, 0) != 0;
  }
  const ::flatbuffers::String *source_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_PATH);
  }
  const ::flatbuffers::String *ast_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AST_PATH);
  }
  const ::flatbuffers::String *object_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OBJECT_PATH);
  }
  const ::flatbuffers::String *sir_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SIR_PATH);
  }
  const ::flatbuffers::String *source_hash() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_HASH);
  }
  const ::flatbuffers::String *ast_hash() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AST_HASH);
  }
  const ::flatbuffers::String *sir_hash() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SIR_HASH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_ENTRY, 1) &&
           VerifyOffset(verifier, VT_ROOT_PATH) &&
           verifier.VerifyString(root_path()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_SHOULD_LOWER, 1) &&
           VerifyOffset(verifier, VT_SOURCE_PATH) &&
           verifier.VerifyString(source_path()) &&
           VerifyOffset(verifier, VT_AST_PATH) &&
           verifier.VerifyString(ast_path()) &&
           VerifyOffset(verifier, VT_OBJECT_PATH) &&
           verifier.VerifyString(object_path()) &&
           VerifyOffset(verifier, VT_SIR_PATH) &&
           verifier.VerifyString(sir_path()) &&
           VerifyOffset(verifier, VT_SOURCE_HASH) &&
           verifier.VerifyString(source_hash()) &&
           VerifyOffset(verifier, VT_AST_HASH) &&
           verifier.VerifyString(ast_hash()) &&
           VerifyOffset(verifier, VT_SIR_HASH) &&
           verifier.VerifyString(sir_hash()) &&
           verifier.EndTable();
  }
};

struct ModuleMetaBuilder {
  typedef ModuleMeta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_is_entry(bool is_entry) {
    fbb_.AddElement<uint8_t>(ModuleMeta::VT_IS_ENTRY, static_cast<uint8_t>(is_entry), 0);
  }
  void add_root_path(::flatbuffers::Offset<::flatbuffers::String> root_path) {
    fbb_.AddOffset(ModuleMeta::VT_ROOT_PATH, root_path);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(ModuleMeta::VT_NAME, name);
  }
  void add_should_lower(bool should_lower) {
    fbb_.AddElement<uint8_t>(ModuleMeta::VT_SHOULD_LOWER, static_cast<uint8_t>(should_lower), 0);
  }
  void add_source_path(::flatbuffers::Offset<::flatbuffers::String> source_path) {
    fbb_.AddOffset(ModuleMeta::VT_SOURCE_PATH, source_path);
  }
  void add_ast_path(::flatbuffers::Offset<::flatbuffers::String> ast_path) {
    fbb_.AddOffset(ModuleMeta::VT_AST_PATH, ast_path);
  }
  void add_object_path(::flatbuffers::Offset<::flatbuffers::String> object_path) {
    fbb_.AddOffset(ModuleMeta::VT_OBJECT_PATH, object_path);
  }
  void add_sir_path(::flatbuffers::Offset<::flatbuffers::String> sir_path) {
    fbb_.AddOffset(ModuleMeta::VT_SIR_PATH, sir_path);
  }
  void add_source_hash(::flatbuffers::Offset<::flatbuffers::String> source_hash) {
    fbb_.AddOffset(ModuleMeta::VT_SOURCE_HASH, source_hash);
  }
  void add_ast_hash(::flatbuffers::Offset<::flatbuffers::String> ast_hash) {
    fbb_.AddOffset(ModuleMeta::VT_AST_HASH, ast_hash);
  }
  void add_sir_hash(::flatbuffers::Offset<::flatbuffers::String> sir_hash) {
    fbb_.AddOffset(ModuleMeta::VT_SIR_HASH, sir_hash);
  }
  explicit ModuleMetaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModuleMeta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModuleMeta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModuleMeta> CreateModuleMeta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool is_entry = false,
    ::flatbuffers::Offset<::flatbuffers::String> root_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    bool should_lower = false,
    ::flatbuffers::Offset<::flatbuffers::String> source_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ast_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> object_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sir_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ast_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sir_hash = 0) {
  ModuleMetaBuilder builder_(_fbb);
  builder_.add_sir_hash(sir_hash);
  builder_.add_ast_hash(ast_hash);
  builder_.add_source_hash(source_hash);
  builder_.add_sir_path(sir_path);
  builder_.add_object_path(object_path);
  builder_.add_ast_path(ast_path);
  builder_.add_source_path(source_path);
  builder_.add_name(name);
  builder_.add_root_path(root_path);
  builder_.add_should_lower(should_lower);
  builder_.add_is_entry(is_entry);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModuleMeta> CreateModuleMetaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool is_entry = false,
    const char *root_path = nullptr,
    const char *name = nullptr,
    bool should_lower = false,
    const char *source_path = nullptr,
    const char *ast_path = nullptr,
    const char *object_path = nullptr,
    const char *sir_path = nullptr,
    const char *source_hash = nullptr,
    const char *ast_hash = nullptr,
    const char *sir_hash = nullptr) {
  auto root_path__ = root_path ? _fbb.CreateString(root_path) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto source_path__ = source_path ? _fbb.CreateString(source_path) : 0;
  auto ast_path__ = ast_path ? _fbb.CreateString(ast_path) : 0;
  auto object_path__ = object_path ? _fbb.CreateString(object_path) : 0;
  auto sir_path__ = sir_path ? _fbb.CreateString(sir_path) : 0;
  auto source_hash__ = source_hash ? _fbb.CreateString(source_hash) : 0;
  auto ast_hash__ = ast_hash ? _fbb.CreateString(ast_hash) : 0;
  auto sir_hash__ = sir_hash ? _fbb.CreateString(sir_hash) : 0;
  return Yogi::Build::CreateModuleMeta(
      _fbb,
      is_entry,
      root_path__,
      name__,
      should_lower,
      source_path__,
      ast_path__,
      object_path__,
      sir_path__,
      source_hash__,
      ast_hash__,
      sir_hash__);
}

struct LinkEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LinkEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_PATH = 6
  };
  Yogi::Build::LinkKind kind() const {
    return static_cast<Yogi::Build::LinkKind>(GetField<int8_t>(VT_KIND, 0));
  }
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           verifier.EndTable();
  }
};

struct LinkEntryBuilder {
  typedef LinkEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(Yogi::Build::LinkKind kind) {
    fbb_.AddElement<int8_t>(LinkEntry::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(LinkEntry::VT_PATH, path);
  }
  explicit LinkEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LinkEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LinkEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LinkEntry> CreateLinkEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Build::LinkKind kind = Yogi::Build::LinkKind_object,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0) {
  LinkEntryBuilder builder_(_fbb);
  builder_.add_path(path);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LinkEntry> CreateLinkEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Yogi::Build::LinkKind kind = Yogi::Build::LinkKind_object,
    const char *path = nullptr) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return Yogi::Build::CreateLinkEntry(
      _fbb,
      kind,
      path__);
}

struct Meta FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MetaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOT_PATH = 4,
    VT_OUTPUT_PATH = 6,
    VT_CACHE_PATH = 8,
    VT_MODULES = 10,
    VT_LINKS = 12
  };
  const ::flatbuffers::String *root_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROOT_PATH);
  }
  const ::flatbuffers::String *output_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OUTPUT_PATH);
  }
  const ::flatbuffers::String *cache_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CACHE_PATH);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>> *modules() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>> *>(VT_MODULES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>> *links() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>> *>(VT_LINKS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ROOT_PATH) &&
           verifier.VerifyString(root_path()) &&
           VerifyOffset(verifier, VT_OUTPUT_PATH) &&
           verifier.VerifyString(output_path()) &&
           VerifyOffset(verifier, VT_CACHE_PATH) &&
           verifier.VerifyString(cache_path()) &&
           VerifyOffset(verifier, VT_MODULES) &&
           verifier.VerifyVector(modules()) &&
           verifier.VerifyVectorOfTables(modules()) &&
           VerifyOffset(verifier, VT_LINKS) &&
           verifier.VerifyVector(links()) &&
           verifier.VerifyVectorOfTables(links()) &&
           verifier.EndTable();
  }
};

struct MetaBuilder {
  typedef Meta Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_root_path(::flatbuffers::Offset<::flatbuffers::String> root_path) {
    fbb_.AddOffset(Meta::VT_ROOT_PATH, root_path);
  }
  void add_output_path(::flatbuffers::Offset<::flatbuffers::String> output_path) {
    fbb_.AddOffset(Meta::VT_OUTPUT_PATH, output_path);
  }
  void add_cache_path(::flatbuffers::Offset<::flatbuffers::String> cache_path) {
    fbb_.AddOffset(Meta::VT_CACHE_PATH, cache_path);
  }
  void add_modules(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>>> modules) {
    fbb_.AddOffset(Meta::VT_MODULES, modules);
  }
  void add_links(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>>> links) {
    fbb_.AddOffset(Meta::VT_LINKS, links);
  }
  explicit MetaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Meta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Meta>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Meta> CreateMeta(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> root_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> output_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cache_path = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>>> modules = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>>> links = 0) {
  MetaBuilder builder_(_fbb);
  builder_.add_links(links);
  builder_.add_modules(modules);
  builder_.add_cache_path(cache_path);
  builder_.add_output_path(output_path);
  builder_.add_root_path(root_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Meta> CreateMetaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *root_path = nullptr,
    const char *output_path = nullptr,
    const char *cache_path = nullptr,
    const std::vector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>> *modules = nullptr,
    const std::vector<::flatbuffers::Offset<Yogi::Build::LinkEntry>> *links = nullptr) {
  auto root_path__ = root_path ? _fbb.CreateString(root_path) : 0;
  auto output_path__ = output_path ? _fbb.CreateString(output_path) : 0;
  auto cache_path__ = cache_path ? _fbb.CreateString(cache_path) : 0;
  auto modules__ = modules ? _fbb.CreateVector<::flatbuffers::Offset<Yogi::Build::ModuleMeta>>(*modules) : 0;
  auto links__ = links ? _fbb.CreateVector<::flatbuffers::Offset<Yogi::Build::LinkEntry>>(*links) : 0;
  return Yogi::Build::CreateMeta(
      _fbb,
      root_path__,
      output_path__,
      cache_path__,
      modules__,
      links__);
}

inline const Yogi::Build::Meta *GetMeta(const void *buf) {
  return ::flatbuffers::GetRoot<Yogi::Build::Meta>(buf);
}

inline const Yogi::Build::Meta *GetSizePrefixedMeta(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Yogi::Build::Meta>(buf);
}

template <bool B = false>
inline bool VerifyMetaBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Yogi::Build::Meta>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMetaBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Yogi::Build::Meta>(nullptr);
}

inline void FinishMetaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Yogi::Build::Meta> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMetaBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Yogi::Build::Meta> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Build
}  // namespace Yogi

#endif  // FLATBUFFERS_GENERATED_META_YOGI_BUILD_H_
