// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAIN_YOGI_MAIN_H_
#define FLATBUFFERS_GENERATED_MAIN_YOGI_MAIN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "ast_generated.h"
#include "meta_generated.h"
#include "sir_generated.h"

namespace Yogi {
namespace Main {

struct Root;
struct RootBuilder;

struct Root FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RootBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BUILD = 4,
    VT_AST = 6,
    VT_SIR = 8
  };
  const Yogi::Build::Meta *build() const {
    return GetPointer<const Yogi::Build::Meta *>(VT_BUILD);
  }
  const Yogi::Ast::AstModule *ast() const {
    return GetPointer<const Yogi::Ast::AstModule *>(VT_AST);
  }
  const Yogi::Sir::Module *sir() const {
    return GetPointer<const Yogi::Sir::Module *>(VT_SIR);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BUILD) &&
           verifier.VerifyTable(build()) &&
           VerifyOffset(verifier, VT_AST) &&
           verifier.VerifyTable(ast()) &&
           VerifyOffset(verifier, VT_SIR) &&
           verifier.VerifyTable(sir()) &&
           verifier.EndTable();
  }
};

struct RootBuilder {
  typedef Root Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_build(::flatbuffers::Offset<Yogi::Build::Meta> build) {
    fbb_.AddOffset(Root::VT_BUILD, build);
  }
  void add_ast(::flatbuffers::Offset<Yogi::Ast::AstModule> ast) {
    fbb_.AddOffset(Root::VT_AST, ast);
  }
  void add_sir(::flatbuffers::Offset<Yogi::Sir::Module> sir) {
    fbb_.AddOffset(Root::VT_SIR, sir);
  }
  explicit RootBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Root> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Root>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Root> CreateRoot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Yogi::Build::Meta> build = 0,
    ::flatbuffers::Offset<Yogi::Ast::AstModule> ast = 0,
    ::flatbuffers::Offset<Yogi::Sir::Module> sir = 0) {
  RootBuilder builder_(_fbb);
  builder_.add_sir(sir);
  builder_.add_ast(ast);
  builder_.add_build(build);
  return builder_.Finish();
}

inline const Yogi::Main::Root *GetRoot(const void *buf) {
  return ::flatbuffers::GetRoot<Yogi::Main::Root>(buf);
}

inline const Yogi::Main::Root *GetSizePrefixedRoot(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Yogi::Main::Root>(buf);
}

template <bool B = false>
inline bool VerifyRootBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Yogi::Main::Root>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedRootBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Yogi::Main::Root>(nullptr);
}

inline void FinishRootBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Yogi::Main::Root> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRootBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Yogi::Main::Root> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Main
}  // namespace Yogi

#endif  // FLATBUFFERS_GENERATED_MAIN_YOGI_MAIN_H_
