POST http://localhost:3456/rpc HTTP/1.1
Content-Type: application/json

{
    "method": "get_user_by_name",
    "params": {
        "name": "anton"
    }
}

###
POST http://localhost:3456/rpc HTTP/1.1
Content-Type: application/json

{
    "method": "yogi.login",
    "params": {
        "githubClientId": "brayhandeaza"
    }
}