// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

// export { LinkEntry } from './meta/link-entry.ts';
// export { LinkKind } from './meta/link-kind.ts';
// export { Meta } from './meta/meta.ts';
// export { ModuleMeta } from './meta/module-meta.ts';
